### ISSUE TITLE
Tester la police Marianne

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-x-ios#44]
Analyser le rendu de la police Marianne sur l'app afin de décider si on l'intègre

**Comment by NicolasBuquet** [comment]
@areox-net Voici ce que ça donne en Marianne (certaines typos dans les boutons ne sont pas remplacées),

![Simulator Screenshot - iPhone 16 - 2024-12-12 at 19 03 26](https://github.com/user-attachments/assets/77bd20ff-0c54-4fff-90f5-870cdc390c4f)
![Simulator Screenshot - iPhone 16 - 2024-12-12 at 19 03 20](https://github.com/user-attachments/assets/f9a51376-bd14-497b-9d98-74ebef58efcf)
![Simulator Screenshot - iPhone 16 - 2024-12-12 at 19 03 14](https://github.com/user-attachments/assets/b7f599d7-e0f4-4be1-8f59-4273458c4104)

**Comment by areox-net** [comment]
Merci @NicolasBuquet.
Pas que les boutons. Les titres page, textes des message. 
Puis il y a un problème de graisse (CF nom user). Je pense que la typo de base doit etre en Semi-bold qui n'existe pas en Marianne. Du coup ça le met en reguliar et c'est pas top.
